[package]
name = "strata"
version = "0.2.0"
edition = "2024"
description = "A fast, polished, personal file manager for Linux"
authors = ["battlemountain2"]
license = "GPL-3.0-or-later"
repository = "https://github.com/battlemountain2/hermes"
keywords = ["file-manager", "gtk4", "linux", "wayland"]
categories = ["filesystem", "gui"]

[dependencies]
cairo-rs = { version = "0.21.5", features = ["pdf", "png"] }
calamine = "0.36.1"
csv = "1.4.0"
fontconfig-sys = { package = "yeslogic-fontconfig-sys", version = "6.0.1" }
gdk-pixbuf = "0.21.5"
geotiff-core = "0.8.1"
gio = { version = "0.21.5", features = ["v2_72"] }
gtk = { package = "gtk4", version = "0.10.3", features = ["v4_12"] }
ignore = "0.4.23"
poppler = { package = "poppler-rs", version = "0.25.0" }
quick-xml = "0.41.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sourceview5 = { version = "0.10.0", features = ["gtk_v4_12"] }
tiff = "0.11"
toml = "0.9"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
zip = "8.6.0"

[build-dependencies]
glib-build-tools = "0.21.0"

[lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"
unused_unsafe = "deny"

[lints.clippy]
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
dbg_macro = "deny"
missing_safety_doc = "deny"
multiple_unsafe_ops_per_block = "deny"
todo = "warn"
undocumented_unsafe_blocks = "deny"
unimplemented = "warn"
unwrap_used = "warn"
